services:
  php-apache:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-app
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - ./src:/var/www/html/
    environment:
      - DB_HOST=mysql
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - app-network

volumes:
  mysql-data:


networks:
  app-network:
    driver: bridge
